### ISSUE TITLE
Provjeriti robot.txt file jel postoji

### ISSUE THREAD

**Issue by brunoAltinet** [altibiz/altibiz-web#13]
Robot.txt file sluzi za indeksiranje googleu, provjeriti imamo li to podrzano i sto je potrebno da se to napravi.

@MajaPol procitai malo o robot.txt fileu

**Comment by brunoAltinet** [comment]
Mora biti sitemap.xml i robot.txt

**Comment by MajaPol** [comment]
Imamo blog_post_sitemap.xml, blog_sitemap.xml i landing_page_sitemap.xml. Robots.txt dozvoljava sve osim /Admin rute.
