### ISSUE TITLE
Na deploymentu je drugaciji font za language switcher

### ISSUE THREAD

**Issue by brunoAltinet** [altibiz/altibiz-web#2]
<img width="322" alt="image" src="https://github.com/altibiz/altibiz-web/assets/4034604/58f4f6df-9a35-4b1e-9453-4d63526084a3">

**Comment by MajaPol** [comment]
Za styling tih linkova sam dodala svoju klasu u theme.css, a na deploymentu je css vuklo iz theme.min.css. Sad sam dodala te klase i u theme.min.css. To bi ujedno trebalo fixati i navigaciju po stranici sa menu linkovima jer nije bila precizna bez anchor klase.
