### ISSUE TITLE
Dupli copyright

### ISSUE THREAD

**Issue by brunoAltinet** [altibiz/altibiz-web#3]
<img width="707" alt="image" src="https://github.com/altibiz/altibiz-web/assets/4034604/e8751084-e1bd-494c-a945-f6a4c54f9ece">

**Comment by MajaPol** [comment]
meni prikazuje ovak 
![image](https://github.com/altibiz/altibiz-web/assets/121028445/71532a93-8d05-4da5-9e84-44aebfc7a853)
