### ISSUE TITLE
Trebamo bolje slike za proizvode

### ISSUE THREAD

**Issue by brunoAltinet** [altibiz/altibiz-web#4]
Genericke zamijeniti sa boljima @MajaPol  vidi sto bi moglo biti okej (moze i placeno)
<img width="552" alt="image" src="https://github.com/altibiz/altibiz-web/assets/4034604/c9cbb711-d5bf-405d-bcb1-92a4d60f6031">

**Comment by MajaPol** [comment]
Prijedlozi za "Upravljanje projektima i kolaboracija":

- https://www.freepik.com/free-vector/business-people-scheduling-work-tasks_4949443.htm#page=3&query=project%20managment&position=2&from_view=search&track=ais
- https://www.istockphoto.com/vector/business-team-working-for-business-process-automation-workflow-project-management-gm1433738921-475561039
(ili neke slično ali uglavnom animirano)

- https://www.istockphoto.com/photo/project-manager-working-on-laptop-and-updating-tasks-and-milestones-progress-gm1411195926-461115694

Prijedlozi za "Pretraživanje i anotacija dokumenata":

- https://www.istockphoto.com/photo/businessman-inspecting-paperwork-document-of-business-data-analysis-working-gm1465316262-497764383

- https://www.freepik.com/free-vector/office-workers-organizing-data-storage-file-archive-server-computer-cartoon-illustration_12699172.htm#query=document%20search&position=31&from_view=search&track=ais

- https://www.freepik.com/premium-photo/electronic-online-doc-man-with-magnifying-glass-data-analytics-annual-report-result-checking-business-documents-scanning_28266002.htm#query=document%20search%20digital&position=0&from_view=search&track=ais

- https://www.freepik.com/premium-ai-image/file-folder-laptop-screen-blue-background-ai-digital-illustration_37858482.htm#page=5&query=document%20search%20annotation&position=40&from_view=search&track=ais

**Comment by brunoAltinet** [comment]
Uzeo sam mjesec dana pretplatu na https://www.freepik.com/ pa cemo skinuti od tamo slike koje trebamo
