### ISSUE TITLE
horizontalni slider na dnu

### ISSUE THREAD

**Issue by DrazenGit** [altibiz/altibiz-web#41]
iz nekog razloga pojavi se slider za horizontalno pomicanje  sadrzaja na dnu stranice. bilo da je cijela sirina ekrana ili ne. 

fix:  pretpostavljam da samo neki element zeza tipa "main" ili sl i samo treba stavit na njega overflow:hidden ili tako nesta

**Comment by MajaPol** [comment]
Trebalo je maknuti "row" klasu iz <main>
