### ISSUE TITLE
Language switcher ne funkcionira na produkciji

### ISSUE THREAD

**Issue by brunoAltinet** [altibiz/altibiz-web#5]
Kliknem na promjenu sajta, ali nesto nece.
Pretpostavljam da je do featura koje treba bolje podesiti?
<img width="117" alt="image" src="https://github.com/altibiz/altibiz-web/assets/4034604/322dd93f-cb80-4958-aa06-5a51d5f3adef">

**Comment by MajaPol** [comment]
ne desi se svaki put greška
